# Generated by Django 3.1.7 on 2021-03-24 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=200, verbose_name='项目名称')),
                ('PNameEN', models.CharField(max_length=200, verbose_name='项目名称英文')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更改时间')),
                ('Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['id', '-CreateTime'],
            },
        ),
        migrations.CreateModel(
            name='Subassembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(max_length=200, verbose_name='组件名')),
                ('SNameEN', models.CharField(max_length=200, verbose_name='组件名英文')),
                ('CodePath', models.CharField(blank=True, max_length=400, null=True, verbose_name='git存储目录')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golang.project')),
            ],
            options={
                'db_table': 'subassembly',
                'ordering': ['-CreateTime'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RName', models.CharField(default='', max_length=200, verbose_name='报告名称')),
                ('CoverageAvg', models.CharField(default='', max_length=200, verbose_name='覆盖率')),
                ('Rtype', models.IntegerField(choices=[(1, '全量'), (2, '增量')], default=1, verbose_name='报告类型')),
                ('RVersion', models.CharField(blank=True, max_length=200, null=True, verbose_name='版本号')),
                ('RstartgitID', models.CharField(blank=True, max_length=200, null=True, verbose_name='git起始commitID')),
                ('RendgitID', models.CharField(blank=True, max_length=200, null=True, verbose_name='git终止commitID')),
                ('RoldUrl', models.CharField(blank=True, max_length=200, null=True, verbose_name='原生报告路径')),
                ('RnewUrl', models.CharField(blank=True, max_length=200, null=True, verbose_name='新报告路径')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('Subassembly', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='golang.subassembly')),
            ],
            options={
                'db_table': 'report',
                'ordering': ['id', '-CreateTime'],
            },
        ),
    ]
