# Generated by Django 3.1.7 on 2021-03-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('golang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
