# Generated by Django 3.1.7 on 2021-03-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golang', '0002_auto_20210324_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subassembly',
            name='CodePath',
            field=models.CharField(max_length=400, verbose_name='git存储目录'),
        ),
    ]
